services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

  product-assets:
    image: nginx:1.27-alpine
    restart: always
    ports:
      - '8081:80'
    volumes:
      - ./devresources/products:/usr/share/nginx/html/products:ro

volumes:
  postgres_data:
