#!/usr/bin/env sh
npx lint-staged

FILES=$(git diff --cached --name-only --diff-filter=ACMR)
PRISMA_SCHEMA=$(printf '%s\n' "$FILES" | grep -Fx 'prisma/schema.prisma' || true)
if [ -n "$PRISMA_SCHEMA" ]; then
  npx prisma validate
fi
